name: test-case
on: push
jobs:
  setup-containers:
    strategy:
      matrix:
          os: [ 'el7']
 
    runs-on: ubuntu-latest
   
    steps:
       - name: Check out Repo
         uses: actions/checkout@v3
       - name: where am i?
         run: pwd;ls -al

       - name: Run Docker Run
         run: curl -s https://raw.githubusercontent.com/cs1867/docker-oneshot-builder/main/build | sh -s - ./test-product ${{ matrix.os }}

   #    - name: tar files
    #     run: tar -cvf pscheduler.tar ./unibuild-repo
        
    #   - name: Archive repo
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: pscheduler-${{ matrix.os }}.tar
    #       path: pscheduler.tar 
   
      # Stash the artifacts
     #  - uses: actions/upload-artifact@v3
     #    with:
     #     # Name the artifact uniquely
     #     name: ${{ github.event.repository.name }}-${{ matrix.os }}
          # Where the finished product lives after the build
     #     path: unibuild-repo
          ## Don't keep these for long.  This is just a test.
     #     retention-days: 5
